import Head from 'next/head';
// import Image from 'next/image';
import styles from '../styles/Home.module.css';
import Layout from '../components/layout';
import React from 'react';
// import useSWR from 'swr';

export default function Home() {
  // const { data, error } = useSWR('/api/characters?cursor=500&limit=20', fetcher);
  // if (error) return <div>An error occured.</div>
  // if (!data) return <div>Loading ...</div>
  // console.log(data);

  return (
    <Layout>
      <div className={styles.container}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className={styles.main}>
          <h1 className={styles.title}>
            Welcome to <a href="https://nextjs.org">Next.js!</a>
          </h1>

          <div>yolo</div>
        </main>

        <footer className={styles.footer}></footer>
      </div>
    </Layout>
  );
}
