import Head from 'next/head';
import styles from '../styles/Home.module.css';
import Layout from '../components/layout';
import React, { useEffect } from 'react';
import { useRouter } from 'next/dist/client/router';
import { useToast } from '@chakra-ui/react';

export default function Home() {
  const router = useRouter();
  const toast = useToast();
  console.log(router.query);

  useEffect(() => {
    if (router.query.l && router.query.l === 't') {
      toast({
        description: 'Please log in to view authorized pages.',
        status: 'error',
        duration: 5000,
        isClosable: true,
      });
      router.push({ pathname: '/' }, undefined, { shallow: true });
    }
  }, [router, router.query.l, toast]);

  return (
    <Layout>
      <div className={styles.container}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className={styles.main}>
          <h1 className={styles.title}>
            Welcome to <a href="https://nextjs.org">Next.js!</a>
          </h1>

          <div>yolo</div>
        </main>

        <footer className={styles.footer}></footer>
      </div>
    </Layout>
  );
}
